### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by marksev1** [apoloval/oac-arduino#1]
Hello,

amazing project you have here, thanks for sharing! Is it possible to also obtain schematics or maybe board designs for the relevant panels?
Basically a "list of materials" on how to do the panels. etc?
Where can I see the progress of the cockpit-build?

**Comment by apoloval** [comment]
Sure! Please visit [www.openairbuscockpit.org](www.openairbuscockpit.org).

**Comment by marksev1** [comment]
I already did, but I see only text, no schematics/wiring diagrams. And I don't see what I need to buy to build the cockpit...

**Comment by apoloval** [comment]
Ok, I assumed you didn't. Sorry for that. 

Some electronic board specifications can be found in [Google Drive](https://drive.google.com/drive/u/0/folders/0B0BJiowk_VgIfjVyN0NDeFhHOUdaOGlWbTdLM3JjNmJOYW1OVDhjdU1DVG5Pb2MxQWpDMEU). My plan is to document them in the website as soon as they are stable enough to be reproduced. That's the case of the [Power Distribution Board](http://openairbuscockpit.org/hardware/electronics/power-distribution-board/).

**Comment by marksev1** [comment]
Great news, thank you very much! Oh I missed that power distro board, I'll read that. 
Thanks for basing your project on arduino and  for opensourcing it.

Do you maybe have an estimate on how much the whole project will cost you, if it is not a secret?

**Comment by apoloval** [comment]
Thank you for using it!

My estimation is around 5.000€. Considering panels, PCBs, materials, projector, computer, Arduino boards and so on. But don't believe me, it's just an estimation.

**Comment by marksev1** [comment]
Thats pretty cheap considering commercial offerings can go in the 35-40000€ range. Hope you can pull it off :D, fingers crossed! 

Got another question, for the PFD, ND and E/WD displays are you just going to use lcd monitors connected to the computer and some special software with which one can align the modules on the screen? (if such a software exists) Or is there another way of doing it? :)

Do you plan to use one high-end computer or multiple?

**Comment by apoloval** [comment]
Yes, I use LCD monitors for glass cockpit displays. The alignment is made manually. Currently I use Prepar3D with Aerosoft Airbus. It's just a matter of moving such displays to 2D panels and align them carefully in the external monitors. 

I only use one high-end computer. Using multiple is pointless as discussed [here](http://openairbuscockpit.org/hardware/computers/).
